service: plerion-beers 

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    BEERS_TABLE: ${self:service}-BeersTable-${sls:stage}
    API_URL: https://0bx12os2ek.execute-api.us-east-1.amazonaws.com/dev/
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: "*"

custom:
  stage: ${opt:stage, 'dev'}
  output:
    file: .serverless/output.json

resources:
  Outputs:
    ApiUrl:
      Description: "The API Gateway URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
  Resources:
    BeersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: beer_id
            AttributeType: S
        KeySchema:
          - AttributeName: beer_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${self:service}-BeersTable-${sls:stage}

plugins:
  - serverless-plugin-typescript
  - serverless-stack-output
  - serverless-offline

functions:
  - ${file(src/functions/index.yml)}
