service: beers 

plugins:
  - serverless-plugin-typescript
  - serverless-stack-output
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

custom:
  stage: ${opt:stage, 'dev'}
  output:
    file: .serverless/output.json

resources:
  Outputs:
    ApiUrl:
      Description: "The API Gateway URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
  Resources:
    BeersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BeersTable
        AttributeDefinitions:
          - AttributeName: beer_id
            AttributeType: S
        KeySchema:
          - AttributeName: beer_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

functions:
  - ${file(src/functions/index.yml)}