# For full config options, check the docs:
#    docs.serverless.com
service: serverless-template 

plugins:
  - serverless-plugin-typescript
  - serverless-stack-output
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

custom:
  stage: ${opt:stage, 'dev'}
  output:
    file: .serverless/output.json

resources:
  Outputs:
    ApiUrl:
      Description: "The API Gateway URL"
      Value:
        Fn::Join:
          - ""
          - - "https://"
            - Ref: ApiGatewayRestApi
            - ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"

functions:
  healthcheck:
    handler: src/functions/healthcheck.healthcheck
    description: Healthcheck to ensure the service is up
    events:
      - http:
          path: healthcheck
          method: get